Claim rewards can select signer
darwinia-network/apps pull request #100
Opened 2022-04-07 03:48 UTC by JayJay1024

2022-04-07 07:41 UTC, sxlwar requested changes

2022-04-07 07:41 UTC, sxlwar commented on src/components/staking/action/ClaimRewards.tsx
> +  useEffect(() => {
为什么需要 subject 转发？只订阅了 complete 和 error 看起来会觉得很奇怪。

tx 的状态变化就可以反映出 loading 的状态，只不过结束状态稍微有些延迟。

如果关心流上的状态，只需要实现个观察者，然后和txProcessObserver合并就行了

2022-04-07 08:17 UTC, JayJay1024 commented on src/components/staking/action/ClaimRewards.tsx
> +  useEffect(() => {
tx可以，不过tx后面会改，不过还没改好可以先用着

2022-04-07 09:05 UTC, JayJay1024 commented on src/components/staking/action/ClaimRewards.tsx
> +  useEffect(() => {
updated

2022-04-08 06:09 UTC, 1022ranji approved these changes

2022-04-08 06:20 UTC, sxlwar approved these changes

2022-04-08 06:22 UTC, merged