chore: max transferrable check
darwinia-network/apps pull request #103
Opened 2022-04-07 06:52 UTC by JayJay1024

2022-04-07 07:22 UTC, sxlwar requested changes

2022-04-07 07:22 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +  const [balances, setBalances] = useState<DeriveBalancesAll | null>(null);
max  就够了， 在这个组件里不会有歧义，transferable 也行，就是敲的字多

2022-04-07 07:22 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +  useEffect(() => {
这 2 个 effect 有一样的问题，没有取消异步操作，会导致 can not update state on unmounted component error

特别是第二个，为什么需要 setTimeout ？严格来说 setTimeout 也需要 clearTimeout 清理

Observable 会简单点

2022-04-07 08:08 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +  useEffect(() => {
这只是Promise不是Subscriptions，没有什么取消异步操作吧；setTimeout是从polkadot/apps拿过来的，setTimeout 0的话不clear应该没什么影响，如果不是0的话可能会「can not update state on unmounted component error」

2022-04-08 06:12 UTC, 1022ranji commented
提示最大可用是789.1，如下图所示：
![image](https://user-images.githubusercontent.com/80877629/162375282-40615b71-0375-4af7-87f6-58cadad99d20.png)
但是转账小于最大可转账时却失败了：https://crab.subscan.io/extrinsic/9941326-1

2022-04-08 06:18 UTC, sxlwar requested changes

2022-04-08 06:18 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +  useEffect(() => {
api.derive.balances.all 如果耗时过长，在 promise resovle之前组件已经销毁，需不需要停止 setBalance 这个动作？

关键的不是setTimeout  延时是不是 0，而是微任务的执行一定在宏任务之后，如果宏任务被取消，那依赖于这个宏任务的微任务不就没有必要执行了么。

如果这里必须借助 setTimeout，总有个理由，但绝对不是因为 polkadot/apps 是这样写

2022-04-08 09:08 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +  useEffect(() => {
这不是说因为 polkadot/apps 是这样写就是正确的，而是我不确定所以按照 polkadot/apps 的拿过来

2022-04-08 09:17 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +  useEffect(() => {
polkadot/apps 计算的balance没有计算bonded/locked，transfer可能`Failed（LiquidityRestrictions）` （https://crab.subscan.io/extrinsic/9941326-1）, 现在改用ring/kton的usable balance

2022-04-08 09:20 UTC, JayJay1024 commented
> 提示最大可用是789.1，如下图所示： ![image](https://user-images.githubusercontent.com/80877629/162375282-40615b71-0375-4af7-87f6-58cadad99d20.png) 但是转账小于最大可转账时却失败了：https://crab.subscan.io/extrinsic/9941326-1

应该修复了，可以在这里 https://apps-piuwr22db-itering.vercel.app/ 测试下

2022-04-08 11:18 UTC, 1022ranji approved these changes

2022-04-11 11:02 UTC, sxlwar approved these changes

2022-04-11 11:03 UTC, merged