feat: validator of input controller
darwinia-network/apps pull request #135
Opened 2022-04-28 10:19 UTC by JayJay1024

2022-04-28 10:46 UTC, ZolaxZola submitted a review, later dismissed

2022-04-28 10:55 UTC, sxlwar requested changes

2022-04-28 10:55 UTC, sxlwar commented on src/utils/helper/validator.ts
> +  return new Promise<string | void>((resolve, reject) => {
1. 函数参数过多的时候用对象传进来
2. 这段显然用async 函数更合适。印象中forkJoin 会 complete，123 行的取消没有必要
3. 这个验证函数并不够纯粹，除了验证逻辑还有取数据、转换，翻译。实际的验证逻辑只是 if else 那段，if 和 else 里还能合并

```ts
({ bondedId, stashId, allBalances, controllerId, accountId}) => string | undefined
```

2022-04-28 10:55 UTC, sxlwar commented on src/components/staking/action/SetController.tsx
> +            {
取数据就在这里

2022-04-29 03:35 UTC, ZolaxZola approved these changes

2022-04-29 04:33 UTC, sxlwar approved these changes

2022-04-29 04:34 UTC, merged