feat: transaction queue
darwinia-network/apps pull request #142
Opened 2022-05-05 01:27 UTC by JayJay1024

2022-05-05 02:26 UTC, ZolaxZola commented
Claim reward时手动选择的账户没有生效

2022-05-05 04:12 UTC, ZolaxZola commented
https://user-images.githubusercontent.com/102211220/166861805-f7940a7b-42d1-43fc-8e0e-1c91230d63ef.mov

Claim弹多个batch时，进度提示文案有点问题。以要弹4个batch为例，第一次claim时显示1/4，领后弹第二次应显示2/4，之后依次3/4，4/4。 目前是显示1/4，1/3，1/2，1/1

2022-05-05 05:50 UTC, JayJay1024 commented
> batch.mov 
> Claim弹多个batch时，进度提示文案有点问题。以要弹4个batch为例，第一次claim时显示1/4，领后弹第二次应显示2/4，之后依次3/4，4/4。 目前是显示1/4，1/3，1/2，1/1

用1/2, 1/3, 1/4这种吧。2,3,4表示队列里还有多少个交易等待签名，签完名就从队列里弹出了。
如果2/4，3/4这种会变的复杂点，这种的话如果当前3/4再加入一个变成3/5和原来的意思有点差别。
而且polka dot apps 也是1/2，1/3，1/4这种的

2022-05-05 06:26 UTC, ZolaxZola commented
> > batch.mov
> > Claim弹多个batch时，进度提示文案有点问题。以要弹4个batch为例，第一次claim时显示1/4，领后弹第二次应显示2/4，之后依次3/4，4/4。 目前是显示1/4，1/3，1/2，1/1
> 
> 用1/2, 1/3, 1/4这种吧。2,3,4表示队列里还有多少个交易等待签名，签完名就从队列里弹出了。 如果2/4，3/4这种会变的复杂点，这种的话如果当前3/4再加入一个变成3/5和原来的意思有点差别。 而且polka dot apps 也是1/2，1/3，1/4这种的

okk👌🏾

2022-05-06 01:24 UTC, sxlwar requested changes

2022-05-06 01:24 UTC, sxlwar commented on .eslintrc.js
>      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
是想要用 && 代替 if吧，虽然可以，但是不建议，JS 语言层面的设计糟粕。语句归语句，表达式归表达式。

2022-05-06 01:24 UTC, sxlwar commented on src/components/widget/QueueStatus.tsx
> +
建议还是用 rxjs，否则手动维护的中间，状态耦合等会使得越往后越难维护，rxjs 本身就是一个queue，无论在时间还是空间上。

polkadot 在这里的实现有待商榷，估计他们现在重构这部分的话也不会采取这种方式

2022-05-06 16:38 UTC, JayJay1024 commented on src/components/widget/QueueStatus.tsx
> +
> 建议还是用 rxjs，否则手动维护的中间，状态耦合等会使得越往后越难维护，rxjs 本身就是一个queue，无论在时间还是空间上。
> 
> polkadot 在这里的实现有待商榷，估计他们现在重构这部分的话也不会采取这种方式

我的想法是，queue得用react的useState存起来，更新的时候才能触发render。
而且有时候只是想从queue中读取tx做一些弹框提示，但是此时并不想从queue中删除这些tx。
rxjs的话subscribe轮询完所有的tx后queue就空了，相当于在queue中删除所有的tx了。
发送tx后的事件这种后续可以改为rxjs（这部分后续有计划改为rxjs）。
是这样？

2022-05-13 01:54 UTC, sxlwar approved these changes, later dismissed

2022-05-13 02:06 UTC, sxlwar approved these changes

2022-05-13 02:08 UTC, merged