feat: fee market
darwinia-network/apps pull request #168
Opened 2022-05-23 02:04 UTC by JayJay1024

2022-06-27 06:24 UTC, sxlwar requested changes

2022-06-27 06:24 UTC, sxlwar commented on src/components/feemarket/Orders.tsx
> +        }
Merge conditions
Do not mix expressions and statements together

2022-06-27 06:24 UTC, sxlwar commented on src/components/feemarket/Orders.tsx
> +      confirmedSlotIndex: node.confirmedSlotIndex,
Why not use the spread operator?

2022-06-27 06:24 UTC, sxlwar commented on src/components/feemarket/Overview.tsx
> +      { date: [], data: [] } as { date: string[]; data: string[] }
date should obviously be in plural

2022-06-27 06:24 UTC, sxlwar commented on src/components/feemarket/Overview.tsx
> +          // eslint-disable-next-line no-magic-numbers
unused comment

2022-06-27 06:24 UTC, sxlwar commented on src/components/widget/fee-market/index.tsx
> +        All
Missing translations?

2022-06-27 08:50 UTC, JayJay1024 commented on src/components/feemarket/Orders.tsx
> +        }
What does `Do not mix expressions and statements together` mean here.
I think returning early can save you from calculating the rest

2022-06-27 09:37 UTC, sxlwar commented on src/components/feemarket/Orders.tsx
> +        }
```js
if (duration && !(duration[0].isBefore(item.createTime) && (!item.finishTime || duration[1].isAfter(item.finishTime)))) {
    return false;
}
```

Even better, we name the condition (e.g: !item.finishTime || duration[1].isAfter(item.finishTime)) to express the intent of the code

2022-06-28 03:32 UTC, JayJay1024 commented on src/components/feemarket/Orders.tsx
> +        }
done

2022-06-28 03:33 UTC, JayJay1024 commented on src/components/feemarket/Orders.tsx
> +      confirmedSlotIndex: node.confirmedSlotIndex,
done

2022-06-28 03:33 UTC, JayJay1024 commented on src/components/feemarket/Overview.tsx
> +      { date: [], data: [] } as { date: string[]; data: string[] }
done

2022-06-28 03:33 UTC, JayJay1024 commented on src/components/feemarket/Overview.tsx
> +          // eslint-disable-next-line no-magic-numbers
resolved

2022-06-28 03:33 UTC, JayJay1024 commented on src/components/widget/fee-market/index.tsx
> +        All
done

2022-06-28 09:24 UTC, sxlwar approved these changes

2022-06-28 09:24 UTC, merged

2022-07-01 02:56 UTC, ZolaxZola commented
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/102211220/176814038-3fcb5261-8a60-4b23-8d97-a6b178770ea8.png">

- [ ] Happens when Switching Network on Relayer Page

2022-07-04 05:14 UTC, JayJay1024 commented
> * Happens when Switching Network on Relayer Page

#260