fix: send ring manual input receiver page error
darwinia-network/apps pull request #202
Opened 2022-06-10 03:18 UTC by JayJay1024

2022-06-10 03:29 UTC, ZolaxZola submitted a review, later dismissed

2022-06-13 02:28 UTC, sxlwar requested changes

2022-06-13 02:28 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +        sub$$ = from(api.tx.balances?.transfer(TEST_ADDR, asset.max).paymentInfo(account)).subscribe((res) => {
TEST_ADDR？

2022-06-13 02:31 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +        sub$$ = from(api.tx.balances?.transfer(TEST_ADDR, asset.max).paymentInfo(account)).subscribe((res) => {
> TEST_ADDR？

yeah, as long as it is a valid address. maybe the name of variable is not so appropriate

2022-06-13 13:41 UTC, HackFisher commented on src/components/account/AssetOverview.tsx
> +        sub$$ = from(api.tx.balances?.transfer(TEST_ADDR, asset.max).paymentInfo(account)).subscribe((res) => {
@JayJay1024 Didn't get it, what is this address? 

So strange, please introduce this modification

2022-06-13 13:42 UTC, HackFisher requested changes

2022-06-13 13:42 UTC, hackfisher commented on src/components/account/AssetOverview.tsx
> +const TEST_ADDR = '1ufRSF5gx9Q8hrYoj7KwpzQzDNqLJdbKrFwC6okxa5gtBRd';
What's this?

2022-06-13 14:08 UTC, JayJay1024 commented
This is used to estimate the gas fee, not the real transaction, as long as this address (TEST_ADDR) is a valid polkadot address.

2022-06-13 14:11 UTC, HackFisher commented
Why not use real address for estimation?

If there is no valid address, just do not show the estimation?

cc @ZolaxZola @1022ranji

2022-06-14 09:31 UTC, ZolaxZola approved these changes

2022-06-14 09:38 UTC, sxlwar approved these changes

2022-06-14 09:45 UTC, merged