chore: zero value doesn't display decimals by default
darwinia-network/apps pull request #232
Opened 2022-06-19 09:12 UTC by JayJay1024

2022-06-19 15:35 UTC, ZolaxZola requested changes
https://user-images.githubusercontent.com/102211220/174488885-c69054dd-8225-4e5b-ab4a-2de1c99de5b4.mov

2022-06-19 16:50 UTC, JayJay1024 commented
> 

transferable is loading

2022-06-20 01:52 UTC, sxlwar approved these changes

2022-06-20 01:52 UTC, sxlwar approved these changes

2022-06-20 01:57 UTC, merged