chore: ring withdraw use dispatch precompiler
darwinia-network/apps pull request #235
Opened 2022-06-20 07:56 UTC by JayJay1024

2022-06-20 07:59 UTC, HackFisher commented on src/components/toolbox/withdraw/Withdraw.tsx
> +const DVM_DISPATCH_ADDRESS = '0x0000000000000000000000000000000000000019';
Add todo comment here: https://github.com/darwinia-network/darwinia-common/pull/1298

2022-06-20 08:00 UTC, HackFisher commented on src/components/toolbox/withdraw/Withdraw.tsx
> +const DVM_DISPATCH_ADDRESS = '0x0000000000000000000000000000000000000019';
Which network is supported?

Crab? or Crab and Pangolin?

2022-06-20 08:02 UTC, hackfisher commented
@ZolaxZola Please help test.  

~~And I think we need to add warn in the ui for the user, about the decimal of the balance is same with Crab chain, should be 9.~~

![image](https://user-images.githubusercontent.com/1070122/174553949-ca6258e4-4584-45af-96b8-034e9e87b157.png)

2022-06-20 08:07 UTC, HackFisher requested changes
It seems that for here, we also support WCKTON?

Please note that CRAB and CKTON are separate and different, the new way of using dispatch is only for CRAB.

CKTON keep unchanged.

2022-06-20 08:21 UTC, JayJay1024 commented
> @ZolaxZola Please help test.
> 
> And I think we need to add warn in the ui for the user, about the decimal of the balance is same with Crab chain, should be 9.
> 
> ![image](https://user-images.githubusercontent.com/1070122/174553949-ca6258e4-4584-45af-96b8-034e9e87b157.png)

Now here the precision is forced to 3.

2022-06-20 08:24 UTC, HackFisher commented
> Now here the precision is forced to 3.

Why introduce this design?

2022-06-20 08:27 UTC, HackFisher submitted a review, later dismissed
LGTM

2022-06-20 08:34 UTC, HackFisher commented
> 
> ~And I think we need to add warn in the ui for the user, about the decimal of the balance is same with Crab chain, should be 9.~
> 


Revoke this suggestion, use does need to care about this.

2022-06-20 09:17 UTC, ZolaxZola commented
> > Now here the precision is forced to 3.
> 
> Why introduce this design?

may cause this problem：cannot transfer the 0.0005 CRAB part
![image](https://user-images.githubusercontent.com/102211220/174568879-53c0a19c-4b85-4f6e-91e9-4f2b68e86d51.png)

2022-06-20 09:21 UTC, ZolaxZola commented
![image](https://user-images.githubusercontent.com/102211220/174569849-1ef1e147-48da-4108-8563-cb45e9593234.png)
From ：0x87F71162cAAC6D9fD8f48C2342509d838578CC81

2022-06-20 14:09 UTC, HackFisher commented
Known issues:

- Pre this pull request
  - Users are sending values to 0x19 (not destination)
  - 0x19 is unstable custom precompile
- Post this pull request
  - Users may not see values in metamask transferring, only calling to some contact 0x19 with un-readable calldata (looks dangerous)
  - In apps, the apps will require to predict the gas fee, it is hard(gas price may change in metamask), so it make the apps hard to calculate how many balances are available for transfer.  (Current solution, keep enough fees for gas cc @JayJay1024 )

2022-06-22 09:47 UTC, HackFisher commented
@JayJay1024 @sxlwar We finally decide to use Dispatch compile, please continue with this PR, thanks.

2022-06-24 01:42 UTC, sxlwar approved these changes

2022-06-24 01:42 UTC, merged