Style update
darwinia-network/apps pull request #25
Opened 2022-03-03 05:02 UTC by JayJay1024

2022-03-03 05:37 UTC, sxlwar commented
控制一下 pr 里修改文件的数量，少量多次

2022-03-03 05:37 UTC, sxlwar requested changes

2022-03-03 05:37 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +  // eslint-disable-next-line complexity
这段复杂度太高了 看逻辑就是 isCrab ? `token-${asset.token.symbol}` : `token-${asset.asset}

2022-03-03 05:37 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
prettyNumber 传参控制小数位
split 之后变量名称明显是有问题的

2022-03-03 05:37 UTC, sxlwar commented on src/components/account/AssetOverview.tsx
> +            <span className="opacity-60">{totalToken.length > 1 ? totalToken[1] : '0'}</span>
整数部分，小数部分应用不同的样式？
有的话我觉得也是个不合理的需求

2022-03-03 05:37 UTC, sxlwar commented on src/components/staking/AssetOverview.tsx
> +      <span className="text-sm opacity-60">{valueSplit.length > 1 ? valueSplit[1] : '0'}</span>
和前边一样

2022-03-03 05:37 UTC, sxlwar commented on src/components/staking/AssetOverview.tsx
又是这段。。。。

2022-03-03 05:37 UTC, sxlwar commented on src/components/staking/overview/StakingOverview.tsx
> +                trailColor="#EBEBEB"
status， strokWdith, trailColor， 是控制样式的吗？如果是，请聚合到一个字段里传进去

2022-03-03 05:37 UTC, sxlwar commented on src/pages/Account.tsx
> +  <span
CustomTab 前边实现过

2022-03-03 05:37 UTC, sxlwar commented on src/pages/Account.tsx
> +    setTabActiveKey(activeKey);
不要单纯的包函数，setTabActiveKey 直接用

2022-03-03 05:37 UTC, sxlwar commented on src/pages/Staking.tsx
> +  <span
。。。。又出现了

2022-03-04 02:28 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +  // eslint-disable-next-line complexity
是的复杂度有点高了。似乎不能`isCrab ? token-${asset.token.symbol} : token-${asset.asset}`。如果`asset.asset`可以cover的话这段就可以直接去掉了

2022-03-04 02:29 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
updated

2022-03-04 02:29 UTC, JayJay1024 commented on src/components/account/AssetOverview.tsx
> +            <span className="opacity-60">{totalToken.length > 1 ? totalToken[1] : '0'}</span>
是的不同样式

2022-03-04 02:30 UTC, JayJay1024 commented on src/components/staking/AssetOverview.tsx
> +      <span className="text-sm opacity-60">{valueSplit.length > 1 ? valueSplit[1] : '0'}</span>
小数和整数不同样式

2022-03-04 02:30 UTC, JayJay1024 commented on src/components/staking/AssetOverview.tsx
updated

2022-03-04 02:30 UTC, JayJay1024 commented on src/components/staking/overview/StakingOverview.tsx
> +                trailColor="#EBEBEB"
这是antd组件的属性

2022-03-04 02:30 UTC, JayJay1024 commented on src/pages/Account.tsx
> +  <span
updated

2022-03-04 02:30 UTC, JayJay1024 commented on src/pages/Account.tsx
> +    setTabActiveKey(activeKey);
updated

2022-03-04 02:31 UTC, JayJay1024 commented on src/pages/Staking.tsx
> +  <span
updated

2022-03-04 03:37 UTC, sxlwar requested changes

2022-03-04 03:37 UTC, sxlwar commented on src/components/widget/FormModal.tsx
> +          >
translate

2022-03-04 03:49 UTC, JayJay1024 commented on src/components/widget/FormModal.tsx
> +          >
fixed

2022-03-07 01:16 UTC, 1022ranji submitted a review, later dismissed

2022-03-07 03:08 UTC, sxlwar approved these changes

2022-03-07 03:12 UTC, merged