Fee market optimization
darwinia-network/apps pull request #266
Opened 2022-07-06 05:53 UTC by JayJay1024

2022-07-08 02:13 UTC, sxlwar requested changes

2022-07-08 02:13 UTC, sxlwar commented on src/components/feemarket/OrderDetail.tsx
> +const getPrioritySlot = (t: TFunction, confirmedSlotIndex?: number | null): string => {
Do not pass 't' function; 

Better to use enum here

2022-07-08 02:13 UTC, sxlwar commented on src/components/feemarket/RelayerDetail.tsx
> +      let ds =
1. use meaningful naming;  what does **ds** mean?
2. DRY

2022-07-08 02:13 UTC, sxlwar commented on src/hooks/pollIntervalQuery.tsx
> +
ts warning

2022-07-08 02:13 UTC, sxlwar commented on src/model/feemarket.ts
> +
Unify enum naming style

2022-07-08 07:22 UTC, ZolaxZola approved these changes

2022-07-11 02:43 UTC, sxlwar approved these changes

2022-07-11 02:43 UTC, merged