Optimize subql code
darwinia-network/apps pull request #279
Opened 2022-07-12 10:09 UTC by JayJay1024

2022-07-13 02:04 UTC, sxlwar requested changes

2022-07-13 02:04 UTC, sxlwar commented on src/model/feemarket.ts
> +export interface RelayerOrdersData {
用泛型简化类型定义，有的类型应该是从其它类型中派生出来的

2022-07-13 02:04 UTC, sxlwar commented on src/utils/fee-market/transform.ts
> +  const day = format(new Date(time), DATE_FORMAT);
函数有副作用，是故意修改 previous？

2022-07-13 02:04 UTC, sxlwar commented on src/utils/fee-market/transform.ts
> +    let orders =
updateOrders 可以柯里化

2022-07-13 02:04 UTC, sxlwar commented on src/utils/fee-market/transform.ts
> +  if (slashAmount) {
大量使用了 断言->累加值 这种逻辑，应该可以抽象出去

2022-07-13 02:45 UTC, JayJay1024 commented on src/utils/fee-market/transform.ts
> +  const day = format(new Date(time), DATE_FORMAT);
> 函数有副作用，是故意修改 previous？
是的，previous是故意修改的

2022-07-13 08:50 UTC, JayJay1024 commented on src/utils/fee-market/transform.ts
> +    let orders =
> updateOrders 可以柯里化

这里updateOrders柯里化好像没什么意义还会多了代码

2022-07-13 09:35 UTC, JayJay1024 commented on src/model/feemarket.ts
> +export interface RelayerOrdersData {
> 用泛型简化类型定义，有的类型应该是从其它类型中派生出来的

这里的类型里面的字段基本都不太一样，有一个OrderDetailBase是可以被其他派生的抽出来了

2022-07-14 03:25 UTC, sxlwar approved these changes

2022-07-14 03:25 UTC, sxlwar commented on src/utils/fee-market/transform.ts
> +    let orders =
原来好像是 5 个参数，这样貌似就没有必要了

2022-07-14 03:26 UTC, merged