feat: pangoro faucet
darwinia-network/apps pull request #281
Opened 2022-07-13 09:57 UTC by cinlk

ORING token faucet

2022-07-14 02:28 UTC, sxlwar requested changes

2022-07-14 02:28 UTC, sxlwar commented on airdrop/api/pangoro/airdrop/state.ts
> +  const recordTime = await client.get(cacheKeyIp);
always use !== or ===

 When == or != must be used, add a comment

2022-07-14 02:28 UTC, sxlwar commented on airdrop/api/pangoro/airdrop/transfer.ts
> +  // const
remove useless comment

2022-07-14 02:28 UTC, sxlwar commented on airdrop/api/pangoro/airdrop/transfer.ts
> +  if (!data || typeof data.address != 'string') {
!=

2022-07-14 02:32 UTC, sxlwar commented
建议不要忽略 lint，可以避免语法上可能导致的 bug

2022-07-14 08:34 UTC, fewensa commented on airdrop/api/grant.ts
> +      origin: 'https://docs.darwinia.network',
Wrong origin?

2022-07-15 09:04 UTC, closed without merging

2022-07-15 09:04 UTC, cinlk commented
refactor in #284