chore: select all when focus or click address input
darwinia-network/apps pull request #36
Opened 2022-03-08 08:54 UTC by JayJay1024

2022-03-08 09:03 UTC, sxlwar requested changes

2022-03-08 09:03 UTC, sxlwar commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
不要用单字母命名，尽管这里作用域是很小

看逻辑就是 map 

`accounts.map(item => ({ value: item.address, label: <IdentAccountAddress account={item} />})`

2022-03-08 09:08 UTC, sxlwar commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
另外考虑下是memo还是 effect， render -> 插件里添加账号-> 会不会把新添加的账号也选中？

2022-03-08 10:21 UTC, JayJay1024 commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
> 另外考虑下是memo还是 effect， render -> 插件里添加账号-> 会不会把新添加的账号也选中？

往输入框里输入地址不会选中

2022-03-08 10:24 UTC, JayJay1024 commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
从下拉列表选择账号也不会全选，只在点击输入框、输入框触发获得焦点时全选

2022-03-08 10:25 UTC, JayJay1024 commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
resolved「单字母命名」和「memo」

2022-03-09 01:04 UTC, 1022ranji approved these changes

2022-03-09 01:11 UTC, sxlwar commented on src/components/widget/form-control/AddressItem.tsx
> +    setOptions(o);
可能没说清楚，我意思是用户去插件里添加新账号，这时accounts 改变， 新账号会不会也被添加进去
回头可以测试下

2022-03-09 01:11 UTC, sxlwar approved these changes

2022-03-09 01:11 UTC, merged