Add files via upload
darwinia-network/apps pull request #413
Opened 2024-06-20 12:44 UTC by Jordy-Baby

2024-06-21 01:34 UTC, hackfisher requested changes

2024-06-21 01:34 UTC, hackfisher commented on src/config/projects.ts
> +  },
```suggestion
  {
    logo: envio,
    name: t("Envio"),
    link: t("https://envio.dev/"),
    description: t(
      "Envio is a modern, multi-chain EVM blockchain indexing framework speed-optimized for querying real-time and historical data."
    ),
    tags: ["Infrastructure", "Tool"],
  },
```

2024-06-21 01:52 UTC, hackfisher requested changes

2024-06-21 01:52 UTC, hackfisher commented on src/config/projects.ts
> +import envio from "..assets/projects/Envio_logo_sqaure.png";
```suggestion
import envio from "../assets/projects/Envio_logo_sqaure.png";
```

2024-06-21 01:57 UTC, hackfisher approved these changes

2024-06-21 01:57 UTC, merged

2024-06-28 10:50 UTC, nblogist commented
@hackfisher as pointed out by @Jordy-Baby that Envio is not visible in the apps.darwinia.network - upon investigation we found out that the checks aren't completely passed and there is a vercel deployment issue: https://github.com/darwinia-network/apps/pull/413/checks can you please have a look at it? - in local deployments Envio shows up fine
![image](https://github.com/darwinia-network/apps/assets/35498810/4b66f174-e69f-415b-892a-83791f3fc879)

2024-07-03 09:57 UTC, Jordy-Baby commented
Hey, @hackfisher, I'm just following up on this. Thanks!

2024-07-03 14:50 UTC, fewensa commented
fix #414 

Thanks for your work @Jordy-Baby  and @nblogist  now you can see it from https://apps.darwinia.network