fix: account actions disabled check
darwinia-network/apps pull request #60
Opened 2022-03-16 05:56 UTC by JayJay1024

- [ ] #50
- [ ] #55

2022-03-16 07:29 UTC, 1022ranji commented
https://darwinia.subscan.io/account/2qdQcyQAvVvyNQcwb2J3T9kYi7yMSniyPNq1ZbqaE1kTpA3o
测试了之后，如果账户设置了其他账户作为 control , 在新的apps中这里显示的controller 地址是错误的，老apps显示的是正确的。
新：
<img width="821" alt="image" src="https://user-images.githubusercontent.com/80877629/158538358-dd091187-1a47-4cd4-9b3e-cf395902f6d6.png">
老：
<img width="970" alt="image" src="https://user-images.githubusercontent.com/80877629/158538412-6dd4fbd0-6f65-483c-99b7-d64ea8e9548b.png">

2022-03-16 08:14 UTC, JayJay1024 commented
> https://darwinia.subscan.io/account/2qdQcyQAvVvyNQcwb2J3T9kYi7yMSniyPNq1ZbqaE1kTpA3o 测试了之后，如果账户设置了其他账户作为 control , 在新的apps中这里显示的controller 地址是错误的，老apps显示的是正确的。 新： <img alt="image" width="821" src="https://user-images.githubusercontent.com/80877629/158538358-dd091187-1a47-4cd4-9b3e-cf395902f6d6.png"> 老： <img alt="image" width="970" src="https://user-images.githubusercontent.com/80877629/158538412-6dd4fbd0-6f65-483c-99b7-d64ea8e9548b.png">

test in this commit please: https://github.com/darwinia-network/apps/commit/c63448971c45698e0d51181d7d08fdadac7ddac7

2022-03-17 01:39 UTC, sxlwar requested changes

2022-03-17 01:39 UTC, sxlwar commented on src/components/staking/action/SetSession.tsx
> +        <AddressItem name="controller" label="Controller account" disabled={true} extra={null} />
这个true不是必须吧，disabled 就是 disabled={true}

2022-03-17 01:39 UTC, sxlwar commented on src/components/staking/action/SetValidator.tsx
> +        type={type}
`isInElection || !controllerAccount || !stashAccount ` 这段前面出现过， 代表了某种业务逻辑的话需要抽出来

2022-03-17 01:39 UTC, sxlwar commented on src/providers/staking.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
取消函数

2022-03-17 02:09 UTC, JayJay1024 commented on src/components/staking/action/SetSession.tsx
> +        <AddressItem name="controller" label="Controller account" disabled={true} extra={null} />
是的不是必须

2022-03-17 02:18 UTC, JayJay1024 commented on src/components/staking/action/SetValidator.tsx
> +        type={type}
这里先不抽，这块业务逻辑还不是很清晰

2022-03-17 05:12 UTC, 1022ranji approved these changes

2022-03-17 08:01 UTC, WoeOm approved these changes

2022-03-17 08:04 UTC, sxlwar approved these changes

2022-03-17 08:05 UTC, merged