Jay fix token unknown
darwinia-network/apps pull request #64
Opened 2022-03-16 10:47 UTC by JayJay1024

2022-03-17 01:27 UTC, sxlwar requested changes

2022-03-17 01:27 UTC, sxlwar commented on src/components/widget/EllipsisMiddle.tsx
> +      txtToEllipse.textContent = txt;
remove unused comments

2022-03-17 01:27 UTC, sxlwar commented on src/components/widget/EllipsisMiddle.tsx
> +          prepEllipse(node, children as string);
类型强转在这里不合适，在 react 中，对于调用者来说 children 这个 prop 就是一个 ReactNode

2022-03-17 01:27 UTC, sxlwar commented on src/providers/account.tsx
> +      const token2 = getToken(chain.tokens, DarwiniaAsset.kton);
命名， 业务上 token1 就是ring

2022-03-17 01:29 UTC, sxlwar commented
不要起 **Jay fix token unknown** 这种标题， changelog 里不会希望出现这种内容 

fix(#xx): xxxxxx

2022-03-17 05:16 UTC, 1022ranji approved these changes, later dismissed

2022-03-17 09:34 UTC, JayJay1024 commented on src/components/widget/EllipsisMiddle.tsx
> +      txtToEllipse.textContent = txt;
resolved

2022-03-17 09:34 UTC, JayJay1024 commented on src/components/widget/EllipsisMiddle.tsx
> +          prepEllipse(node, children as string);
resolved

2022-03-17 09:34 UTC, JayJay1024 commented on src/providers/account.tsx
> +      const token2 = getToken(chain.tokens, DarwiniaAsset.kton);
resolved

2022-03-17 10:01 UTC, sxlwar requested changes

2022-03-17 10:01 UTC, sxlwar commented on src/components/widget/EllipsisMiddle.tsx
```js
<EllipsisMiddle>
    <span>xxxxx</span>
</EllipsisMiddle>
```
结果会是什么 ？
要不就另加一个新 prop: string 不要用 children，而不是只把textContent 的类型声明改成 ReactNode

2022-03-17 10:12 UTC, JayJay1024 commented on src/components/widget/EllipsisMiddle.tsx
这段是从旧版本来的么。
这里原来有点问题，按照这里的计算把children看做了string。
有想过加多一个value prop，不过用到这个组件的地方还挺太多
![image](https://user-images.githubusercontent.com/21007682/158787119-9c337401-0c3f-4328-a666-93e1e09935c3.png)

2022-03-17 10:13 UTC, JayJay1024 commented on src/components/widget/EllipsisMiddle.tsx
明天看看，这样的话就加多一个prop: `value: string`

2022-03-18 02:52 UTC, sxlwar approved these changes

2022-03-18 03:04 UTC, merged