Number decimal check
darwinia-network/apps pull request #72
Opened 2022-03-18 09:08 UTC by JayJay1024

2022-03-18 09:31 UTC, 1022ranji submitted a review, later dismissed

2022-03-18 10:05 UTC, sxlwar requested changes

2022-03-18 10:05 UTC, sxlwar commented on src/components/staking/overview/Validators.tsx
>            const author = lastHeader.author.toString();
仅仅是包装参数没有必要， 可以直接传第二个参数，也可以向左柯里化 prettyNumber ，formatNum 这种实现纯属自已给自己找麻烦，而且这个命名也有待商榷

2022-03-19 04:06 UTC, sxlwar approved these changes

2022-03-19 04:07 UTC, merged